server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/api/policies/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: quote-service
          uri: lb://quote-service
          predicates:
            - Path=/api/quotes/**
        - id: claim-service
          uri: lb://claim-service
          predicates:
            - Path=/api/claims/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**
        - id: risk-analysis-service
          uri: lb://risk-analysis-service
          predicates:
            - Path=/api/risk/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
