server:
  port: 9200

spring:
  application:
    name: policy-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ${DB_USERNAME:policy_user}
    password: ${DB_PASSWORD:policy_password}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25
