spring:
  application:
    name: quote-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/quotedb
      database: quotedb
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${jwt.secret:rEfdWEFerf34r34FERfe3f34fERfefewfWEFWEFwefWEFWEFwef34F34f3}
  config:
    import: "configserver:http://localhost:8888"

server:
  port: 9300
  servlet:
    context-path: /

services:
  customer-service:
    url: http://localhost:8081
  policy-service:
    url: http://localhost:8082
  risk-analysis-service:
    url: http://localhost:9600

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    com.insurtech.quote: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    org.springframework.security: INFO
    org.springframework.web.reactive: INFO
    reactor.netty: INFO