server:
  port: 9000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ${DB_USERNAME:auth_user}
    password: ${DB_PASSWORD:auth_password}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
