spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: PAYMENT_SCHEMA
    password: ayabrea
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${jwt.secret:rEfdWEFerf34r34FERfe3f34fERfefewfWEFWEFwefWEFWEFwef34F34f3}
  # Configuración Kafka (para desarrollo local)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
  config:
    import: "configserver:http://localhost:8888"

# Propiedad para deshabilitar Kafka (usar con @ConditionalOnProperty en KafkaConfig)
kafka:
  enabled: false  # Cambiar a true cuando quieras activar Kafka

# Como ya creaste la tabla, podemos habilitar el servicio de bloqueo
lock:
  enabled: true

server:
  port: 8083
  servlet:
    context-path: /

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25

services:
  customer-service:
    url: http://localhost:8081
  policy-service:
    url: http://localhost:8082
  claim-service:
    url: http://localhost:8084

jwt:
  secret: rEfdWEFerf34r34FERfe3f34fERfefewfWEFWEFwefWEFWEFwef34F34f3
  issuer: insurtech-auth
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    com.insurtech.payment: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configuración específica para simulación de pasarela de pago
payment:
  gateway:
    simulation:
      success-rate: 90
      timeout-ms: 500
    retry:
      max-attempts: 3