spring:
  application:
    name: claim-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: CLAIM_SCHEMA
    password: ayabrea
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${jwt.secret:rEfdWEFerf34r34FERfe3f34fERfefewfWEFWEFwefWEFWEFwef34F34f3}
  # Configuración Kafka (valores mínimos para evitar errores)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: claim-service-group
      auto-offset-reset: earliest
  config:
    import: "configserver:http://localhost:8888"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Propiedad para deshabilitar Kafka (usar con @ConditionalOnProperty en KafkaConfig)
kafka:
  enabled: false

server:
  port: 8084
  servlet:
    context-path: /

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25

batch:
  claim:
    chunk-size: 100
    grid-size: 4

services:
  customer-service:
    url: http://localhost:8081
  policy-service:
    url: http://localhost:8082
  document-service:
    url: http://localhost:8085

app:
  events:
    enabled: false
  document:
    storage:
      path: /tmp/claim-documents
  claims:
    high-value-threshold: 10000.00

jwt:
  secret: rEfdWEFerf34r34FERfe3f34fERfefewfWEFWEFwefWEFWEFwef34F34f3
  issuer: insurtech-auth
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    com.insurtech.claim: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.batch: INFO
    org.hibernate.SQL: DEBUG