spring:
  application:
    name: catastro-service
  config:
    import: "configserver:http://localhost:8888"

server:
  port: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
