spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: CUSTOMER_SCHEMA
    password: ayabrea
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json
          secret: ${jwt.secret:rEfdWEFerf34r34FERfe3f34fERfefewfWEFWEFwefWEFWEFwef34F34f3}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: customer-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  config:
    import: "configserver:http://localhost:8888"

server:
  port: 8081
  servlet:
    context-path: /

# Habilitación de eventos
app:
  events:
    enabled: true

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25

# Configuración JWT
jwt:
  secret: rEfdWEFerf34r34FERfe3f34fERfefewfWEFWEFwefWEFWEFwef34F34f3
  issuer: insurtech-auth
  expiration: 86400000

tracing:
  zipkin:
    url: http://localhost:9411/api/v2/spans

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    com.insurtech.customer: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.kafka: INFO
