server:
  port: 9900

spring:
  application:
    name: monitoring-service
  influxdb:
    url: http://localhost:8086
    username: ${INFLUX_USER:admin}
    password: ${INFLUX_PASSWORD:admin}
    database: metrics
    retention-policy: autogen
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 30

management:
  metrics:
    export:
      influx:
        enabled: true
        step: 10s
